//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_khepri : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 MovePosition
        {
            get
            {
                return SteamVR_Actions.khepri_MovePosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean Boost
        {
            get
            {
                return SteamVR_Actions.khepri_Boost;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeMode
        {
            get
            {
                return SteamVR_Actions.khepri_ChangeMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.khepri_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Down
        {
            get
            {
                return SteamVR_Actions.khepri_Down;
            }
        }
        
        public virtual SteamVR_Action_Vector2 CameraPosition
        {
            get
            {
                return SteamVR_Actions.khepri_CameraPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftLaserToogle
        {
            get
            {
                return SteamVR_Actions.khepri_LeftLaserToogle;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightLaserToogle
        {
            get
            {
                return SteamVR_Actions.khepri_RightLaserToogle;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSelect
        {
            get
            {
                return SteamVR_Actions.khepri_LeftSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSelect
        {
            get
            {
                return SteamVR_Actions.khepri_RightSelect;
            }
        }
    }
}
